# Generated by Django 6.0.3 on 2026-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tag', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='service',
            field=models.CharField(choices=[('sweets', 'Sweets order'), ('room', 'Room booking')], default='sweets', max_length=20),
        ),
    ]
